@base_url=http://localhost:8081
POST {{base_url}}/todos
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE2NjgwNDc1NDZ9.11izsLQw5udB89Rb8pmKAaW9TL1PxSR2aRiukfr3B4Q

{
    "text": "test 3"
}
